name: kz_game
description: "Nederlandse speurtocht-game voor kinderen"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  audioplayers: ^6.4.0
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/loadscreen_portrait.png
    - assets/loadscreen_landscape.png
    - assets/roads.png
    - assets/animals.png
    - assets/word.png
    - assets/ticks.png
    - assets/spelregels.png
    - assets/spelregels_EN.png
    - assets/tips.png
    - assets/tips_EN.png
    # removed missing Tinkerbell assets
    # removed missing tinkerbell image
    - assets/uiltje.png
    - assets/habitat/world.png
    - assets/fotoframe.png
    - assets/bosgebied.geojson
    - assets/bosdieren.geojson
    - assets/bosdieren2.geojson
    - assets/fauna.geojson
    - assets/searcharea2.geojson
    - assets/fauna2.geojson
    - assets/fauna3.geojson
    - assets/KZ_locatie.geojson
    - assets/maps/colscreen.png
    - assets/areas/search_area.geojson
    - assets/quests/
    - assets/animals/icons_300/
    - assets/animals/icons_300_silhouette/
    - assets/animals/master/
    - assets/audio/
    - assets/footstep.png
    - assets/route.geojson
    - assets/rotate.png
    - assets/habitat/
